version: 2

project_name: port-user

# Build settings
builds:
  - id: port-user
    main: ./main.go
    binary: port-user
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: windows
        goarch: arm64

# Archive settings (tar.gz, zip)
archives:
  - id: port-user
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - "./*.txt"
      - "./LICENSE"

# NFPM settings (deb, rpm)
nfpms:
  - id: linux-package
    package_name: "{{ .ProjectName }}"
    file_name_template: "{{ .PackageName }}_{{ .Version }}_{{ .Architecture }}.{{ .Format }}"
    formats:
      - deb
      - rpm
    license: MIT
    maintainer: Your Name <you@example.com>
    description: A cross-platform CLI tool to find processes using TCP/UDP ports.
    vendor: Your Company
    dependencies:
      - systemd
    conflicts:
      - old-port-user
    replaces:
      - old-port-user

# macOS Installer (pkg)
installers:
  - id: macos-installer
    # Only run on darwin builds
    builds:
      - darwin/amd64
      - darwin/arm64
    type: pkg
    name_template: "{{ .ProjectName }}-{{ .Version }}-macos-{{ .Arch }}"
    script: |
      #!/bin/sh
      echo "Installing port-user to /usr/local/bin..."
      mkdir -p /usr/local/bin/
      cp "$INSTALLER_PATH/port-user" /usr/local/bin/
      chmod +x /usr/local/bin/port-user

# Docker image (optional)
dockers:
  - image_templates:
      - "ghcr.io/yourusername/port-user:latest"
      - "ghcr.io/yourusername/port-user:{{ .Tag }}"

# GitHub Release settings
release:
  draft: false
  disable: false