version: 2

project_name: port-user

release:
  draft: false
  prerelease: false
  disable: false

builds:
  - id: port-user
    main: ./main.go
    binary: port-user
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: port-user
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - "./LICENSE"
      - "./README.md"

nfpms:
  - id: linux-package
    package_name: "{{ .ProjectName }}"
    file_name_template: "{{ .PackageName }}_{{ .Version }}_{{ .Architecture }}.{{ .Format }}"
    formats:
      - deb
      - rpm
    license: MIT
    maintainer: dolastack dolastack@gmail.com
    description: A cross-platform CLI tool to find processes using TCP/UDP ports.

installers:
  - id: macos-installer
    builds:
      - darwin/amd64
      - darwin/arm64
    type: pkg
    name_template: "{{ .ProjectName }}-{{ .Version }}-macos-{{ .Arch }}"
    script: |
      #!/bin/sh
      echo "Installing port-user to /usr/local/bin..."
      mkdir -p /usr/local/bin/
      cp "$INSTALLER_PATH/port-user" /usr/local/bin/
      chmod +x /usr/local/bin/port-user

checksum:
  name_template: "checksums.txt"