name: Build, Package & Release port-user

on:
  push:
    branches:
      - main
  release:
    types:
      - created
      - published

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install GoReleaser
        run: |
          curl -sL https://git.io/goreleaser  | GOPROXY=${GOPROXY} bash

      - name: Run GoReleaser
        id: goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}